services:
  db:
    image: postgres:15-alpine
    container_name: campamento_postgres
    restart: always
    environment:
      POSTGRES_USER: camp_user
      POSTGRES_PASSWORD: camp_password
      POSTGRES_DB: campamento_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camp_user -d campamento_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: campamento_api
    restart: always
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://camp_user:camp_password@db:5432/campamento_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: